### ISSUE TITLE
Writing Unit Tests for LifelongClassificationForest

### ISSUE THREAD

**Issue by latasianguy** [neurodata/progressive-learning#100]
To write unit tests for LifelongClassificationForest in [forest.py](https://github.com/neurodata/progressive-learning/blob/master/proglearn/network.py). Part of Issue #49 . Code in progress [here](https://github.com/latasianguy/progressive-learning/blob/unittest-lifelongclassificationforest/tests/test_lifelongclassificationforest.py).

**Comment by latasianguy** [comment]
@jdey4, should I write more unit tests for this? I only checked that the setup/initialization for the class is correct

**Comment by levinwil** [comment]
Closing, as PR #190 has been merged
