### ISSUE TITLE
purge all data from repo

### ISSUE THREAD

**Issue by jovo** [neurodata/progressive-learning#101]
repo should only have code, and possibly figures, and minimal data required to reproduce the figure itself

**Comment by jovo** [comment]
@jdey4 this should be closed when a PR is merged that removes all the data.

**Comment by jdey4** [comment]
@jovo all the data from the experiment folder is removed.

**Comment by levinwil** [comment]
Once this task is finished, I think we should also add *.pickle to the 'gitignore' to prevent further additions to storing pickle files on git. Does that seem appropriate?

**Comment by jovo** [comment]
yup, sounds good.

On Thu, Sep 10, 2020 at 3:53 PM Will LeVine <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> Once this task is finished, I think we should also add *.pickle to the
> 'gitignore' to prevent further additions to storing pickle files on git.
> Does that seem appropriate?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F101%23issuecomment-690682537&data=02%7C01%7Cjovo%40jhu.edu%7C57c0ae4501284315858308d855c33af9%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637353644273939931&sdata=19FHPD76H5q3tmzCDDfcrsY3AjdxzttfhdVOmjH8C%2BA%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4VTKDHRSNXVDMFS46LSFEVERANCNFSM4RDBQQFQ&data=02%7C01%7Cjovo%40jhu.edu%7C57c0ae4501284315858308d855c33af9%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637353644273939931&sdata=uqaeSsO3qTNjCPhhOWOuU5GiMKejahrqa%2BYynTPCaL0%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!

**Comment by jovo** [comment]
ok, link to the PR corresponding to removing everything when you close this then.

**Comment by jdey4** [comment]
@jovo  I was directly committing to the master. I added '*.pickle' to the .gitignore already and all the pickle files were removed.

**Comment by jovo** [comment]
please stop. committing to master. that goes to everybody.  time to get
better github practices starting today please.

On Fri, Sep 11, 2020 at 10:56 AM Jayanta Dey <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7Ccbd54cc8d3e24e515a9b08d85662d06d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354329685921258&sdata=tFfYPlCDeyHRRQZQSGR3hccso9AAc27sg8fttNK2lGA%3D&reserved=0>
> I was directly committing to the master. I added '*.pickle' to the
> .gitignore already and all the pickle files were removed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F101%23issuecomment-691144449&data=02%7C01%7Cjovo%40jhu.edu%7Ccbd54cc8d3e24e515a9b08d85662d06d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354329685921258&sdata=jSWh4qLVezxT2AXmqjv%2F5GjsxRNe5JeZjhqIb1t6NQQ%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4TP3HH3XPEGF4P7BVTSFI3ALANCNFSM4RDBQQFQ&data=02%7C01%7Cjovo%40jhu.edu%7Ccbd54cc8d3e24e515a9b08d85662d06d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354329685931249&sdata=e56uKoETQl8lqWsoYhdeqg%2BEDzH8aMc8fercKjpZQFk%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!

**Comment by jdey4** [comment]
@jovo all the data are purged. I am sorry that I failed to make a PR. Should we close this issue?

**Comment by jovo** [comment]
yes

On Mon, Sep 14, 2020 at 10:55 AM Jayanta Dey <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7C0afbfb4142a3473264ac08d858be45cd%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637356921518496943&sdata=Jj6tjPokZC73W3KrLj6xDtG0aZLaRXOtTSsfSBFcEzU%3D&reserved=0>
> all the data are purged. I am sorry that I failed to make a PR. Should we
> close this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F101%23issuecomment-692111983&data=02%7C01%7Cjovo%40jhu.edu%7C0afbfb4142a3473264ac08d858be45cd%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637356921518506937&sdata=S%2FtmBC3Of1ukkf53wsmxocXJOR%2FYeuwvs6Xh3CpYpF4%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4Q7NQGBLQAX75S5FMDSFYVG5ANCNFSM4RDBQQFQ&data=02%7C01%7Cjovo%40jhu.edu%7C0afbfb4142a3473264ac08d858be45cd%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637356921518506937&sdata=yX1Gd6kdI9DUowy6lSSGsiYuJa%2Bb86AKZwzo88LccGc%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!
