### ISSUE TITLE
Document KNNRegressionDecider and LinearRegressionDecider in decider.py

### ISSUE THREAD

**Issue by parthgvora** [neurodata/progressive-learning#103]
Fill out docstrings for KNNRegressionDecider and LinearRegressionDecider classes in decider.py.

**Comment by levinwil** [comment]
@parthgvora These two functions are going to be purged from main very soon, which would make this task very confusing. Is/are there other function(s) you could document instead?

**Comment by parthgvora** [comment]
My bad! I picked them at random. I'll make a new ticket for some other functions.

**Comment by levinwil** [comment]
No worries! That is our fault for having code on master that will go away. Thanks for your patience!
