### ISSUE TITLE
Reproduce label shuffle experiment in Jupiter Notebook

### ISSUE THREAD

**Issue by mkusman1** [neurodata/progressive-learning#123]
For sprint 0, issue [#41](https://github.com/neurodata/progressive-learning/issues/41), 
Tutorial for [lable shuffle](https://github.com/neurodata/progressive-learning/tree/master/experiments/label_shuffle) (sprint 0) in Jupitor notebook
@jdey4

**Comment by levinwil** [comment]
@mkusman1 why is this closed? Do you have a link to the label shuffle tutorial in a Jupiter notebook?

**Comment by levinwil** [comment]
duplicate issue of #75
