### ISSUE TITLE
Add class attributes to UF class docstring

### ISSUE THREAD

**Issue by levinwil** [neurodata/progressive-learning#125]
Please see #105 for further details and tips. This is in regards to the forest.py file.

**Comment by levinwil** [comment]
@bstraus1 Given that you documented UncertaintyForest, could you please do this at your soonest convenience?

**Comment by bstraus1** [comment]
Will do! One question: What are the attributes that are specifically tied to the class?

**Comment by levinwil** [comment]
Any variable that begins with 'self.' in any of the UncertaintyForest functions

**Comment by bstraus1** [comment]
Can I be assigned to this issue? (post-closing)
