### ISSUE TITLE
make a single example unit test

### ISSUE THREAD

**Issue by jovo** [neurodata/progressive-learning#126]

**Comment by levinwil** [comment]
@jovo What do you mean by 'single example'?

**Comment by jovo** [comment]
just any unit test, so people know what a unit test looks like for this
repo.

On Fri, Sep 11, 2020 at 12:53 PM Will LeVine <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7C89772ca8075c463b37ab08d85673434f%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354400340798452&sdata=10zzya1OGY4sXjHKi9T7uw5%2BMzuwLQAX5fMBDLHTRJs%3D&reserved=0>
> What do you mean by 'single example'?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F126%23issuecomment-691205166&data=02%7C01%7Cjovo%40jhu.edu%7C89772ca8075c463b37ab08d85673434f%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354400340808447&sdata=%2Bn1Y9uT6FkOfBLachNaHqrpg7xpXcAhjH2fFav3QhfE%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4QTYPKGZMJQBOC45F3SFJIZ7ANCNFSM4RH22J2A&data=02%7C01%7Cjovo%40jhu.edu%7C89772ca8075c463b37ab08d85673434f%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354400340808447&sdata=K8RMgtBhCb7thrTrCBoVU093fSNF0jVBQY%2F15mE9kk0%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!

**Comment by levinwil** [comment]
Do you want it to be a unit test or a system test?

**Comment by jovo** [comment]
see issue title

On Fri, Sep 11, 2020 at 12:57 PM Will LeVine <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> Do you want it to be a unit test or a system test?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F126%23issuecomment-691207033&data=02%7C01%7Cjovo%40jhu.edu%7C5d45728a2d1341980e0a08d85673cc92%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354402635451986&sdata=a2OUeMkwB1uo2nB6LNh4%2Fcrj%2B2VyHcBsE6IU2jn9iq4%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4TFNRDCYQBAQMVXGIDSFJJIJANCNFSM4RH22J2A&data=02%7C01%7Cjovo%40jhu.edu%7C5d45728a2d1341980e0a08d85673cc92%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637354402635451986&sdata=bz%2FO9aYUjuTK3cWTJVI5KltrdZdITwF5vfNYHQEHZng%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!

**Comment by levinwil** [comment]
Just made a pull request at the following link: https://github.com/neurodata/progressive-learning/pull/129
