### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by mkusman1** [neurodata/progressive-learning#178]
I am currently working on writing a tutorial for the label shuffle experiment and was wondering if anyone encountered this issue:  
I get this error: from .base import <....> ImportError: attempted relative import with no known parent package jupiter. 
Moreover,  for some reason python3 setup.py install does not work (screenshots attached)

I am using Jupiter notebook in Anaconda3 on Windows 10, Python 3.8.3.

![image](https://user-images.githubusercontent.com/69170008/93350832-e5a00200-f7ed-11ea-916c-cbf5d18b49dd.png)
![image](https://user-images.githubusercontent.com/69170008/93350914-f81a3b80-f7ed-11ea-8f0b-92d54628fc7a.png)

**Comment by mkusman1** [comment]
@jdey4 @sampan501

**Comment by mkusman1** [comment]
I was using conda powershell and I believe it already uses virtual environment

**Comment by sampan501** [comment]
what happens when you write `python --version`

**Comment by mkusman1** [comment]
It outputs: Python 3.8.3
Should I downgrade Python to 3.6 v?

**Comment by mkusman1** [comment]
I also ran pip freeze and there is no proglearn package

**Comment by PSSF23** [comment]
The codes are outdated. It should be `proglearn.progressive_learner` instead of `progressive_learner`

**Comment by mkusman1** [comment]
I think it resolves the issue partially. But I still can't download the package.
![image](https://user-images.githubusercontent.com/69170008/93351901-1af91f80-f7ef-11ea-8d28-a41244bba1f7.png)

**Comment by PSSF23** [comment]
Check out the current version of label_shuffle experiment: https://github.com/neurodata/progressive-learning/blob/master/experiments/label_shuffle/label_shuffle_exp.py

**Comment by PSSF23** [comment]
try `import proglearn`

**Comment by jdey4** [comment]
@mkusman1 if you can't install the package, the problem will not be solved.

**Comment by mkusman1** [comment]
I tried to import it but it doesn't work

**Comment by PSSF23** [comment]
please show the screenshot.

**Comment by mkusman1** [comment]
I think the issue now is installing the package itself 
![image](https://user-images.githubusercontent.com/69170008/93352720-fd788580-f7ef-11ea-8d9c-f69ff390d0d1.png)

**Comment by mkusman1** [comment]
@PSSF23 Also, how come my version of label_shuffle_exp.py is outdated? I used github desktop today to clone the repo on my computer

**Comment by PSSF23** [comment]
@mkusman1 maybe you cloned your fork instead of the newest ndd master branch. Jayanta updated the experiment files recently.

**Comment by mkusman1** [comment]
@PSSF23 It was a master branch, I just doublechecked. Thats weird

**Comment by sampan501** [comment]
Did you `git pull` recently?

**Comment by mkusman1** [comment]
@sampan501  I did it today

**Comment by PSSF23** [comment]
@mkusman1 Let's try to solve the package problem first, try `pip list` and see if you have `proglearn` or `setuptools`? Also `pip --version` to see which version of python it is associated.

**Comment by jdey4** [comment]
There is another way around. Install the dependencies separately and use relative import like from .proglearn import SimpleAverage. But the installation problem must be solved.

**Comment by mkusman1** [comment]
pip list output:
setuptools   49.2.0.post20200714
no proglearn

pip --version output:
pip 20.1.1 from C:\Users\MK\anaconda3\lib\site-packages\pip (python 3.8)

**Comment by mkusman1** [comment]
@jdey4  I am sorry, I don't quite understand what you mean by "Install the dependencies separately and use relative import like from .proglearn import SimpleAverage"

**Comment by jdey4** [comment]
We can avoid installing the proglearn package. If you have all the required packages like tensorflow and others installed, you can tell the compiler the path from where to import the modules.

**Comment by mkusman1** [comment]
@jdey4  So it is not possible to install the package in another way?

**Comment by mkusman1** [comment]
@jdey4 @sampan501  
pip freeze output: 
proglearn==0.0.1

I made a change in setup file. There was an encoding issue: 
with open("README.md", encoding="utf8") as f:
    LONG_DESCRIPTION = f.read()

**Comment by sampan501** [comment]
it should be fine as a temporary fix. I'm going to leave this issue open for further investigation
