### ISSUE TITLE
Fix line 69 deciders.py bug

### ISSUE THREAD

**Issue by levinwil** [neurodata/progressive-learning#192]
Voters are outputting different length posteriors since some voter are given a subset of the classes

**Comment by levinwil** [comment]
Please talk to Yuta about reproducing the error. The simple description of the issue is that voters are outputting posteriors of different lengths because some voters only see a subset of the classes in their fit function (due to random chance in the sampling). So, the easy solution is:
1. In the progressive learner, whenever you add a task, figure out the unique label values (using np.unique). Feed that to the initialization of each voter (in the same way that we feed the exact same unique label values vector to deciders). Save it as a class member variable in the initialization function of the voter (perhaps call it "self.total_labels")
2. For the voters (both TreeClassificationVoter and KNNClassificationVoter), in the fit function, check to see if the labels fed to the initialization function that you saved in step 1 are all present in the examples provided to the fit function. If there is/are label(s) that should've been present but isn't/aren't, figure out which label(s) they were and what their indices were with respect to self.total_labels. This is quite simple: literally just check, for each label in self.total_labels, if it that label is present in the labels of the examples fed to the fit function. If not, save the index of that missing label as a class member variable (e.g. if self.total_labels = [3, 5, 6, 8] and 5 is missing, set 'self.missing_label_indices = [1], since 5 is at the 1st index of self.total_labels; if 3 and 8 are missing, set 'self.missing_label_indices = [0, 3], since 3 and 8 are at 0th and 3rd indices of self.total_labels, respectively.
3. At inference time, in the predict_proba function (currently called "vote" but will be changed per Issue #226), after make sure that, for each example, you insert a 0 in all of the indices in self.missing_label_indices. This says "hey, I know I'm supposed to report back the probability of belonging to the class at this index, but I didn't see any examples from that class. So, I'll just put a 0 there.

**Comment by bstraus1** [comment]
I’m interested in working on this but currently have other work slated for the next three weeks. If no one else wants it, I can work on it then.

**Comment by ykobaya9** [comment]
I have been working on it for the past week or so, and implemented most of the changes. I was wondering if there was a method for internally calculating total_labels and passing it into voter_kwargs during initialization within progressive_learner.py. Right now, I have to manually specify the total_labels when calling add_task from my experiment file.

**Comment by levinwil** [comment]
total_labels = no.unique(y)

This is in the instructions under Solution, step 1

**Comment by ykobaya9** [comment]
Thank you, I was wondering more about where to specify the voter_kwargs in progressive_learner.py. This is because I fear that adding a new field total_labels to initialization for voter will cause most of the current experiment files to not work, since they don't specify a total_labels when adding a task. An alternative is to have a default value for self.total_labels in the voter class.

**Comment by levinwil** [comment]
Please see lines 38-44 of this file for an example of how I implemented that default in deciders:

https://github.com/neurodata/progressive-learning/blob/master/proglearn/deciders.py

**Comment by levinwil** [comment]
It’s a good thing to make sure we don’t break the tests that currently exist. I agree that we should have defaults. I should’ve been more clear in my instructions.

Also, within forest.py and network.py, we can explicitly make sure that ‘classes’ is fed to voter_kwargs, very similar to this line: https://github.com/neurodata/progressive-learning/blob/master/proglearn/forest.py#L92
