### ISSUE TITLE
document the progl repo: add the overview and documentation sections

### ISSUE THREAD

**Issue by bstraus1** [neurodata/progressive-learning#68]

**Comment by levinwil** [comment]
Per the suggestion of some folks at Microsoft and in agreement with jovo, if possible, the documentation and overview should focus on the following two files:
1. https://github.com/neurodata/progressive-learning/blob/will_dev/proglearn/forest.py
2. https://github.com/neurodata/progressive-learning/blob/will_dev/proglearn/network.py

**Comment by bstraus1** [comment]
Can I be assigned to this issue? I think this connects with issue #4

**Comment by levinwil** [comment]
Closing, since these sections have been created
