### ISSUE TITLE
For sake of consistency, add is_fitted function to decider in files {base, decider}.py

### ISSUE THREAD

**Issue by levinwil** [neurodata/progressive-learning#71]

**Comment by tliu68** [comment]
Can I take this issue (assuming it's 1 person's work)? For clarification, do you mean these two files [1](https://github.com/neurodata/progressive-learning/blob/master/proglearn/base.py) & [2](https://github.com/neurodata/progressive-learning/blob/master/proglearn/transformers.py)?

**Comment by levinwil** [comment]
Those were the files I initially referenced in the issue title. However, the second file, transformer.py, was the wrong file. I meant to say decider.py: https://github.com/neurodata/progressive-learning/blob/master/proglearn/deciders.py
