### ISSUE TITLE
document forest.py

### ISSUE THREAD

**Issue by bstraus1** [neurodata/progressive-learning#73]
> [https://github.com/neurodata/progressive-learning/blob/will_dev/proglearn/forest.py](url)
Per #4 and #68

**Comment by bstraus1** [comment]
Issue #94 is more accurately the portion of this issue that I will be completing. I've removed myself from this issue.

**Comment by p-teng** [comment]
@jdey4 Could I be assigned to this issue for sprint 0?

**Comment by levinwil** [comment]
Closing, since forest.py has been documented
