### ISSUE TITLE
document network.py

### ISSUE THREAD

**Issue by bstraus1** [neurodata/progressive-learning#74]
[https://github.com/neurodata/progressive-learning/blob/will_dev/proglearn/network.py](url)
Per #4 and #68

**Comment by bstraus1** [comment]
Is this the kind of documentation we are looking for?
<img width="388" alt="Screen Shot 2020-09-07 at 5 42 34 PM" src="https://user-images.githubusercontent.com/37525700/92417706-86792800-f131-11ea-876f-025cc0d64197.png">

**Comment by bstraus1** [comment]
Issue #94 is more accurately the portion of this issue that I will be completing. I've removed myself from this issue.

**Comment by RebeccaYin7** [comment]
@jdey4 can I please be assigned to this issue? thanks.

**Comment by bstraus1** [comment]
@RebeccaYin7 It is probably best to choose a function within network.py, make a sub-issue, then get assigned that.

**Comment by RebeccaYin7** [comment]
@bstraus1 sounds good. I've created issue [#150](https://github.com/neurodata/progressive-learning/issues/150).

**Comment by levinwil** [comment]
Closing, since network.py has been documented
