### ISSUE TITLE
Document NeuralClassificationTransformer and TreeClassificationTransformer classes in transformers.py

### ISSUE THREAD

**Issue by Michael-Ainsworth** [neurodata/progressive-learning#77]
https://github.com/neurodata/progressive-learning/blob/master/proglearn/transformers.py
per issue #4

**Comment by Michael-Ainsworth** [comment]
Could I be assigned this issue?

**Comment by Michael-Ainsworth** [comment]
@jdey4 , my pull request was merged! Could this issue be closed?

**Comment by levinwil** [comment]
Closing, since these functions have been documented.
