### ISSUE TITLE
kernel density forests

### ISSUE THREAD

**Issue by jovo** [neurodata/progressive-learning#80]
replaces boxcar filters with gaussians

**Comment by bstraus1** [comment]
Can I be assigned this issue for sprint1?

**Comment by jovo** [comment]
sorry, this is a double one, it was also here: https://github.com/neurodata/progressive-learning/issues/118
and already taken :(
We can talk tomorrow after class if you want.

**Comment by levinwil** [comment]
@jovo could I be part of the conversation that you have tomorrow after class?

**Comment by jovo** [comment]
yes please!

On Thu, Sep 10, 2020 at 11:21 PM Will LeVine <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=02%7C01%7Cjovo%40jhu.edu%7C68f528b1bbfe43f8c9d508d85601d7d9%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637353913194171056&sdata=MKv4wqp%2FNNGzWBVU0BsAY0C5qxSUyIjTTr1L9wWKQxs%3D&reserved=0>
> could I be part of the conversation that you have tomorrow after class?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fprogressive-learning%2Fissues%2F80%23issuecomment-690850023&data=02%7C01%7Cjovo%40jhu.edu%7C68f528b1bbfe43f8c9d508d85601d7d9%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637353913194181055&sdata=IAse7dLw5w4eeniltc8Uw3preXHbWVpzhYdOxrCSGuI%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4UVFFFWPGRYFR6HE43SFGJVLANCNFSM4Q44DUFQ&data=02%7C01%7Cjovo%40jhu.edu%7C68f528b1bbfe43f8c9d508d85601d7d9%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637353913194181055&sdata=OK9yaq4mScNBc14crEbEpJHrmgmptNUvZKSk50K%2BxSA%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
Think I can do better? Tell me how <https://forms.gle/iEad8byD89eTPdYx6>!
