### ISSUE TITLE
Write unit test functions for TreeClassificationVoter

### ISSUE THREAD

**Issue by ypeng22** [neurodata/progressive-learning#82]
Write unit tests for all functions of TreeClassificationVoter/ located at: https://github.com/neurodata/progressive-learning/blob/master/proglearn/voters.py 
in a new file called test_treeclassification under : 
https://github.com/neurodata/progressive-learning/blob/master/tests/

**Comment by levinwil** [comment]
Closing since this seems to have been mostly resolved
