### ISSUE TITLE
Write unit test functions for KNNClassificationVoter

### ISSUE THREAD

**Issue by williamrxu** [neurodata/progressive-learning#96]
Write unit tests for functions in the KNNClassificationVoter class from https://github.com/neurodata/progressive-learning/blob/master/proglearn/voters.py. Unit tests are drafted in https://github.com/williamrxu/progressive-learning/blob/master/tests/test_voters.py.

**Comment by levinwil** [comment]
Hey! If possible, could you please use the following framework to write unit tests: https://docs.python.org/3/library/unittest.html

**Comment by williamrxu** [comment]
Understood!

**Comment by williamrxu** [comment]
Closed per PR #165

**Comment by levinwil** [comment]
@williamrxu This issue appears to be completed, as per the files you linked above. Do you think it would be appropriate for me to close this issue?

**Comment by williamrxu** [comment]
Yes, this issue is ready to be closed.
